# Generated by Django 5.0.6 on 2024-07-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MasterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_tool_name", models.CharField(max_length=255)),
                ("descriptions", models.TextField(blank=True, null=True)),
                (
                    "payment_condition",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "useable_for",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("charges", models.CharField(blank=True, max_length=255, null=True)),
                ("review", models.CharField(blank=True, max_length=255, null=True)),
                ("tool_link", models.TextField(blank=True, null=True)),
                (
                    "major_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecommendationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_tool_name", models.CharField(max_length=255)),
                ("descriptions", models.TextField(blank=True, null=True)),
                (
                    "useable_for",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "master_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.masterdata",
                    ),
                ),
            ],
        ),
    ]
