# Generated by Django 5.0.6 on 2024-09-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_masterdata_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationdata",
            name="major_category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
